Change order of inheritance for `StrawberryDjangoField`
The current MRO of `StrawberryDjangoField` has it applying pagination before the `StrawberryDjangoFieldBase.get_queryset` resolves. Since pagination does array slicing, if you have a custom `get_queryset` defined on the type, it will raise the following error:
```
AssertionError: Cannot filter a query once a slice has been taken.
```

By changing the MRO to have pagination come after field base, we will avoid this issue, since pagination will be applied last